#
# Copyright (C) 2024 G. Allen Morris III
#
# This is free software, licensed under the Apache License, Version 2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI netwatch config app for js based luci
LUCI_DEPENDS:=+luci-base +netwatch-daemon
LUCI_PKGARCH:=all

PKG_MAINTAINER:=G. Allen Morris III <gam3@gam3.net>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
